services:
  db:
    image: postgres:16 # Specifies the PostgreSQL image and version
    environment:
      POSTGRES_USER: khiem # Defines the database user
      POSTGRES_PASSWORD: 123456 # Defines the password for the user
      POSTGRES_DB: khiem-db # Defines the default database name
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists database data
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    networks:
      - khiem
    
  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Map host port 8080 to container port 80
      - "443:443" # Uncomment for HTTPS
    volumes:
      - ./nginx:/etc/nginx/conf.d # Mount your Nginx configuration
    # depends_on:
      # - frontend # Ensure backend service starts before Nginx
    networks:
      - khiem

networks:
  khiem:
    driver: bridge

volumes:
  postgres_data: